Beta
dawidbar/AdminPanel pull request #1
Opened 2019-01-19 13:02 UTC by dawidbar

Mam problem z tą sekcją z liczbami pod kalendarzem. Nie mogę wypozycjonować cyfr na prawą stronę

2019-01-19 18:25 UTC, michal-bootcamp requested changes
Pare uwag ogolnych:
1. nie masz nic w styleguide
2. w scss nie uzywasz zmiennych sassowych
3. w pliku style.scss powinienes miec tylko importy, a kod podzielony na pliki z komponentami, mozesz zasugerowac sie organizacja plikow przez bootstrapa: https://github.com/twbs/bootstrap/tree/v4-dev/scss

2019-01-19 18:25 UTC, michal-bootcamp commented on js/script.js
> +$(window).on('load resize', function () {
masz kod w jQuery ale nie dolaczasz jQuery do strony i w konsoli pokazuje sie blad

2019-01-19 18:25 UTC, michal-bootcamp commented on sass/_layout.scss
> +    .col-sm-#{$i} {
dlaczego generujesz dwa razy grida `-sm-`? Tu i w media query?

2019-01-19 18:25 UTC, michal-bootcamp commented on index.html
> +    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
do czego uzywasz bootstrapa?

2019-01-19 18:25 UTC, michal-bootcamp commented on index.html
>      <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
dolacz tez odpowiednie grubosci Roboto, ktore powinny byc uzywane na stronie

2019-01-19 18:25 UTC, michal-bootcamp commented on index.html
> +            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
z wszystkich svg usun `id` (generowany przy eksporcie, powtarza sie i nie jest potrzebny)

2019-01-19 18:25 UTC, michal-bootcamp commented on sass/style.scss
> +    box-shadow: 1px 1px 1px rgba($color: #000000, $alpha: 0.2);
ta linijka jest niepoprawna

2019-01-19 23:14 UTC, dawidbar commented on index.html
> +    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
Do responsywnej tabelki z tego linku: https://codepen.io/dawidbar/pen/aPemqv

2019-01-21 12:05 UTC, dawidbar commented on js/script.js
> +$(window).on('load resize', function () {
dodane

2019-01-21 12:08 UTC, dawidbar commented on index.html
>      <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
dodane

2019-01-21 12:09 UTC, dawidbar commented on index.html
> +            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
zrobione

2019-01-21 12:11 UTC, dawidbar commented on sass/style.scss
> +    box-shadow: 1px 1px 1px rgba($color: #000000, $alpha: 0.2);
box-shadow? Czemu?

2019-01-23 10:36 UTC, michal-bootcamp commented on index.html
> +    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
ok

2019-01-23 10:37 UTC, michal-bootcamp commented on sass/style.scss
> +    box-shadow: 1px 1px 1px rgba($color: #000000, $alpha: 0.2);
ta czesc: `rgba($color: #000000, $alpha: 0.2);`

2019-01-23 10:42 UTC, michal-bootcamp commented on sass/style.scss
> +    box-shadow: 1px 1px 1px rgba($color: #000000, $alpha: 0.2);
aaa sorry, bo Ty przeciez uzywasz sassowej funkcji - juz zajarzylem, nie bylo tematu :)
https://sass-lang.com/documentation/Sass/Script/Functions.html#rgba-instance_method

2019-01-23 10:55 UTC, michal-bootcamp requested changes
1. zmien nazwy plikow scss dodajac na poczatku podkreslenie, zeby sass wiedzial, ze to pliki czesciowe do importow, bo aktualnie tworzy Ci css'owe odpowiedniki dla wszystkich tych plikow w katalogu css i robi sie smietnik
2. zaktualizuj sobie task `watch:sassprefixer`, zeby obserowal tez zmiany w podkatalogach i w plikach o dowolnych nazwach z rozszerzeniem .scss: `onchange sass/**/*.scss`

2019-01-23 10:55 UTC, michal-bootcamp commented on sass/_layout.scss
> +    .col-sm-#{$i} {
wyrzuc te petle for, bo masz to juz w mixinie i mixiny mozesz przeniesc do osobnego pliku z mixinami

2019-01-23 10:55 UTC, michal-bootcamp commented on sass/style.scss
> +@import "sass/variables";
nie dodawaj katalogu `sass` bo w tym pliku w nim jestes, samo `@import "variables";`

2019-01-23 10:55 UTC, michal-bootcamp commented on index.html
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
ladowanie jQuery przenies pod ladowanie styli css zeby strona nie czekala na js zeby wyswietlic wyglad (css)

2019-01-23 10:59 UTC, michal-bootcamp commented
aha wurzuc jeszcze `.row { ... }` ze style.scss bo masz to juz w `_layout.scss`

2019-01-23 13:25 UTC, dawidbar commented on sass/style.scss
> +@import "sass/variables";
ok

2019-01-23 13:26 UTC, dawidbar commented on index.html
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
ok

2019-02-05 10:03 UTC, michal-bootcamp requested changes
dopracuj prosze 
1. `index.html`:
- niech linki beda klikalnymi linkami, 
- daty w datapickerze wg projektu sa wyrownane do lewej
- w topbarze nie ma zadnych hoverow
2. `styleguide.html`:
- powinny tam byc reuzywalne elementy ze strony index.html

Ponadto:
- folder `.vscode` nie powinien byc obecny w repo zdalnym
- nazwy plikow czesciowych scss w katalogu `pages` nazywaj zaczynajac od podkreslenia

2019-02-05 10:03 UTC, michal-bootcamp commented on personaldata.html
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
js pod css

2019-02-05 10:03 UTC, michal-bootcamp commented on sass/style.scss
> +@import "sass/pages/personal-data";
sass w tej sciezce niepotrzebny, startujesz z poziomu sass wiec wystarczy, ze do importow napiszesz np `"pages/banners"`

2019-02-05 10:03 UTC, michal-bootcamp commented on sass/sections/_side-bar.scss
> +.sidebar, .jsss {
Tutaj jest powod tego, ze menu sie nie rozwija/zwija. Jak przyjrzysz sie w devtoolsach, to klikajac na ikone dodajesz lub zabierasz klase `jsss` z elementu z klasa `sidebar` wiec ten selektor powinien wygladac tak: `.sidebar.jsss` - chcesz ostylowac element z klasa sidebar i jsss na raz, a nie element z klasa sidebar i element z klasa jsss

2019-02-05 12:12 UTC, dawidbar commented on personaldata.html
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
ok

2019-02-05 12:12 UTC, dawidbar commented on sass/style.scss
> +@import "sass/pages/personal-data";
ok

2019-02-05 12:17 UTC, dawidbar commented on sass/sections/_side-bar.scss
> +.sidebar, .jsss {
Teraz jest super :)

2019-02-06 08:30 UTC, michal-bootcamp requested changes
sprawdz prosze zgodnosc styli z projektem, poki co widze takie rzeczy:
- grubosci naglowkow sa inne niz w projekcie
- grubosc fonta na buttonie tez inna niz w projekcie
- hovery linkow w tabeli inne niz na projekcie
- tabela jest ucinana od spodu: https://scr.hu/2220yn1

2019-02-06 08:30 UTC, michal-bootcamp commented on styleguide.html
> +        <title>Document</title>
dodaj css do styleguide'a

2019-02-08 16:37 UTC, merged